# DO NOT EDIT. This file was automatically generated by generate_prose_mirror_classes.py.
from typing import Any, List, Literal, Optional, Union

from pydantic import BaseModel


# Common parent class for all Tiptap nodes
class TiptapNode(BaseModel):
    # Base class for all Tiptap/ProseMirror nodes
    pass


# Node group unions for convenience

InlineNode = Union["HardbreakNode", "TextNode"]
BlockNode = Union[
    "ParagraphNode",
    "BlockquoteNode",
    "BulletlistNode",
    "CodeblockNode",
    "HeadingNode",
    "HorizontalruleNode",
    "OrderedlistNode",
    "ImageNode",
]
ListNode = Union["BulletlistNode", "OrderedlistNode"]


class ParagraphNode(TiptapNode):
    type: Literal["paragraph"] = "paragraph"
    content: Optional[List["InlineNode"]]


class BlockquoteNode(TiptapNode):
    type: Literal["blockquote"] = "blockquote"
    content: List["BlockNode"]


class BulletlistNode(TiptapNode):
    type: Literal["bulletList"] = "bulletList"
    content: List["ListitemNode"]


class CodeblockNodeAttrs(BaseModel):
    language: Optional[Any] = None


class CodeblockNode(TiptapNode):
    type: Literal["codeBlock"] = "codeBlock"
    attrs: CodeblockNodeAttrs = CodeblockNodeAttrs()
    content: Optional[List["TextNode"]]


class DocNode(TiptapNode):
    type: Literal["doc"] = "doc"
    content: List["BlockNode"]


class HardbreakNode(TiptapNode):
    type: Literal["hardBreak"] = "hardBreak"


class HeadingNodeAttrs(BaseModel):
    level: int = 1


class HeadingNode(TiptapNode):
    type: Literal["heading"] = "heading"
    attrs: HeadingNodeAttrs = HeadingNodeAttrs()
    content: Optional[List["InlineNode"]]


class HorizontalruleNode(TiptapNode):
    type: Literal["horizontalRule"] = "horizontalRule"


class ListitemNode(TiptapNode):
    type: Literal["listItem"] = "listItem"
    content: Union["ParagraphNode", Optional[List["BlockNode"]]]


class OrderedlistNodeAttrs(BaseModel):
    start: int = 1
    type: Optional[Any] = None


class OrderedlistNode(TiptapNode):
    type: Literal["orderedList"] = "orderedList"
    attrs: OrderedlistNodeAttrs = OrderedlistNodeAttrs()
    content: List["ListitemNode"]


class TextNode(TiptapNode):
    type: Literal["text"] = "text"
    text: str


class ImageNodeAttrs(BaseModel):
    src: Optional[Any] = None
    alt: Optional[Any] = None
    title: Optional[Any] = None


class ImageNode(TiptapNode):
    type: Literal["image"] = "image"
    attrs: ImageNodeAttrs = ImageNodeAttrs()
