# DO NOT EDIT. This file was automatically generated by generate_prose_mirror_classes.py.
from typing import List, Optional, Tuple, Union

from pydantic import validator
from typing_extensions import Literal

from schema.block import BaseAttrs, Block


# Common parent class for all Tiptap nodes
class TiptapNode(Block):
    pass


BlockNode = Union[
    "BlockquoteNode",
    "BulletlistNode",
    "CodeblockNode",
    "HeadingNode",
    "HorizontalruleNode",
    "ImageNode",
    "ImageheaderNode",
    "OrderedlistNode",
    "ParagraphNode",
    "TableNode",
]
ListNode = Union["BulletlistNode", "OrderedlistNode"]
InlineNode = Union["HardbreakNode", "TextNode"]


class ParagraphNode(Block):
    type: Literal["paragraph"] = "paragraph"
    content: Optional[List["InlineNode"]]
    attrs: Optional[BaseAttrs] = None


class BlockquoteNode(Block):
    type: Literal["blockquote"] = "blockquote"
    content: List["BlockNode"]
    attrs: Optional[BaseAttrs] = None


class BulletlistNode(Block):
    type: Literal["bulletList"] = "bulletList"
    content: List["ListitemNode"]
    attrs: Optional[BaseAttrs] = None


class CodeblockNode(Block):
    type: Literal["codeBlock"] = "codeBlock"
    content: Optional[List["TextNode"]]

    class Attrs(BaseAttrs):
        language: Optional[str] = None

    attrs: Optional[Attrs] = None


class HardbreakNode(Block):
    type: Literal["hardBreak"] = "hardBreak"
    attrs: Optional[BaseAttrs] = None


class HeadingNode(Block):
    type: Literal["heading"] = "heading"
    content: Optional[List["InlineNode"]]

    class Attrs(BaseAttrs):
        level: Optional[int] = 1

    attrs: Optional[Attrs] = None


class HorizontalruleNode(Block):
    type: Literal["horizontalRule"] = "horizontalRule"
    attrs: Optional[BaseAttrs] = None


class ListitemNode(Block):
    type: Literal["listItem"] = "listItem"
    content: List[Union["BlockNode", "ParagraphNode"]]

    @validator("content")
    def check_content(cls, v):
        if not v:
            return v
        if v[0].type != "paragraph":
            raise ValueError("First child must be a paragraph")
        for node in v[1:]:
            if node.type != "block":
                raise ValueError("Subsequent children must be blocks")
        return v

    attrs: Optional[BaseAttrs] = None


class OrderedlistNode(Block):
    type: Literal["orderedList"] = "orderedList"
    content: List["ListitemNode"]

    class Attrs(BaseAttrs):
        start: Optional[int] = 1
        type: Optional[str] = None

    attrs: Optional[Attrs] = None


class TextNode(Block):
    type: Literal["text"] = "text"
    text: str


class ImageNode(Block):
    type: Literal["image"] = "image"

    class Attrs(BaseAttrs):
        src: Optional[str] = None
        alt: Optional[str] = None
        title: Optional[str] = None

    attrs: Optional[Attrs] = None


class TableNode(Block):
    type: Literal["table"] = "table"
    content: List["TablerowNode"]
    attrs: Optional[BaseAttrs] = None

    def get_text(self) -> Optional[str]:
        return "\n".join([child.get_text() for child in self.content])


class TablerowNode(Block):
    type: Literal["tableRow"] = "tableRow"
    content: Optional[List[Union["TablecellNode", "TableheaderNode"]]]
    attrs: Optional[BaseAttrs] = None

    def get_text(self) -> Optional[str]:
        return " | ".join([child.get_text() for child in self.content])


class TablecellNode(Block):
    type: Literal["tableCell"] = "tableCell"
    content: List["BlockNode"]

    class Attrs(BaseAttrs):
        colspan: Optional[int] = 1
        rowspan: Optional[int] = 1
        colwidth: Optional[str] = None

    attrs: Optional[Attrs] = None


class TableheaderNode(Block):
    type: Literal["tableHeader"] = "tableHeader"
    content: List["BlockNode"]

    class Attrs(BaseAttrs):
        colspan: Optional[int] = 1
        rowspan: Optional[int] = 1
        colwidth: Optional[str] = None

    attrs: Optional[Attrs] = None


class ImageheaderNode(Block):
    type: Literal["imageHeader"] = "imageHeader"
    content: Tuple["ImageNode", "ImageNode", "ImageNode"]
    attrs: Optional[BaseAttrs] = None
